[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc_version = "0.8.21"
evm_version = "shanghai"
optimizer_runs = 9_999
bytecode_hash = "none"
# via_ir = true

remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
    '@rari-capital/solmate/=lib/solmate/',
    'contracts/=contracts/',
    'murky/=lib/murky/src/',
]

gas_reports = ["*"]

# See more config options https://github.com/gakonst/foundry/tree/master/config